extern const GeoLayout ccm_area_1_geo[];
extern const GeoLayout ccm_area_1[];
extern const Collision ccm_area_1_collision[];
extern const MacroObject ccm_area_1_macro_objs[];
extern u8 ccm_dl_dark_world_edge_top_ci4[];
extern u8 ccm_dl_dark_world_edge_top_ci4_pal_rgba16[];
extern u8 ccm_dl_dark_world_edge_corner_ci4[];
extern u8 ccm_dl_dark_world_edge_corner_ci4_pal_rgba16[];
extern u8 ccm_dl_dark_world_edge_ci4[];
extern u8 ccm_dl_dark_world_edge_ci4_pal_rgba16[];
extern Vtx ccm_dl_Cube_mesh_layer_1_vtx_0[1584];
extern Gfx ccm_dl_Cube_mesh_layer_1_tri_0[];
extern Vtx ccm_dl_Cube_mesh_layer_1_vtx_1[356];
extern Gfx ccm_dl_Cube_mesh_layer_1_tri_1[];
extern Vtx ccm_dl_Cube_mesh_layer_1_vtx_2[2646];
extern Gfx ccm_dl_Cube_mesh_layer_1_tri_2[];
extern Gfx mat_ccm_dl_f3dlite_material[];
extern Gfx mat_revert_ccm_dl_f3dlite_material[];
extern Gfx mat_ccm_dl_f3dlite_material_001[];
extern Gfx mat_revert_ccm_dl_f3dlite_material_001[];
extern Gfx mat_ccm_dl_f3dlite_material_002[];
extern Gfx mat_revert_ccm_dl_f3dlite_material_002[];
extern Gfx ccm_dl_Cube_mesh_layer_1[];
extern Gfx ccm_dl_material_revert_render_settings[];
