extern const GeoLayout castle_grounds_area_1_geo[];
extern const GeoLayout castle_grounds_area_1[];
extern const Collision castle_grounds_area_1_collision[];
extern const MacroObject castle_grounds_area_1_macro_objs[];
extern u8 castle_grounds_dl_library_floor_rgba16[];
extern u8 castle_grounds_dl_library_books_ci4[];
extern u8 castle_grounds_dl_library_books_ci4_pal_rgba16[];
extern u8 castle_grounds_dl_library_walls_ci4[];
extern u8 castle_grounds_dl_library_walls_ci4_pal_rgba16[];
extern u8 castle_grounds_dl_library_doors_ci4[];
extern u8 castle_grounds_dl_library_doors_ci4_pal_rgba16[];
extern u8 castle_grounds_dl_library_book_ci4[];
extern u8 castle_grounds_dl_library_book_ci4_pal_rgba16[];
extern Vtx castle_grounds_dl_Cube_mesh_layer_1_vtx_0[116];
extern Gfx castle_grounds_dl_Cube_mesh_layer_1_tri_0[];
extern Vtx castle_grounds_dl_Cube_mesh_layer_1_vtx_1[16];
extern Gfx castle_grounds_dl_Cube_mesh_layer_1_tri_1[];
extern Vtx castle_grounds_dl_Cube_mesh_layer_1_vtx_2[22];
extern Gfx castle_grounds_dl_Cube_mesh_layer_1_tri_2[];
extern Vtx castle_grounds_dl_Cube_mesh_layer_1_vtx_3[43];
extern Gfx castle_grounds_dl_Cube_mesh_layer_1_tri_3[];
extern Vtx castle_grounds_dl_Cube_mesh_layer_2_vtx_0[15];
extern Gfx castle_grounds_dl_Cube_mesh_layer_2_tri_0[];
extern Gfx mat_castle_grounds_dl_f3dlite_material[];
extern Gfx mat_revert_castle_grounds_dl_f3dlite_material[];
extern Gfx mat_castle_grounds_dl_f3dlite_material_002[];
extern Gfx mat_revert_castle_grounds_dl_f3dlite_material_002[];
extern Gfx mat_castle_grounds_dl_f3dlite_material_001[];
extern Gfx mat_revert_castle_grounds_dl_f3dlite_material_001[];
extern Gfx mat_castle_grounds_dl_f3dlite_material_003_layer2[];
extern Gfx mat_revert_castle_grounds_dl_f3dlite_material_003_layer2[];
extern Gfx mat_castle_grounds_dl_f3dlite_material_004[];
extern Gfx mat_revert_castle_grounds_dl_f3dlite_material_004[];
extern Gfx castle_grounds_dl_Cube_mesh_layer_1[];
extern Gfx castle_grounds_dl_Cube_mesh_layer_2[];
extern Gfx castle_grounds_dl_material_revert_render_settings[];
