extern const GeoLayout bob_area_1_geo[];
extern const GeoLayout bob_area_1[];
extern const Collision bob_area_1_collision[];
extern const MacroObject bob_area_1_macro_objs[];
extern const GeoLayout bob_area_2_geo[];
extern const GeoLayout bob_area_2[];
extern const Collision bob_area_2_collision[];
extern const MacroObject bob_area_2_macro_objs[];
extern const GeoLayout bob_area_3_geo[];
extern const GeoLayout bob_area_3[];
extern const Collision bob_area_3_collision[];
extern const MacroObject bob_area_3_macro_objs[];
extern const GeoLayout bob_area_4_geo[];
extern const GeoLayout bob_area_4[];
extern const Collision bob_area_4_collision[];
extern const MacroObject bob_area_4_macro_objs[];
extern const GeoLayout bob_area_5_geo[];
extern const GeoLayout bob_area_5[];
extern const Collision bob_area_5_collision[];
extern const MacroObject bob_area_5_macro_objs[];
extern u8 bob_dl_library_walls_ci4[];
extern u8 bob_dl_library_walls_ci4_pal_rgba16[];
extern u8 bob_dl_library_doors_ci4[];
extern u8 bob_dl_library_doors_ci4_pal_rgba16[];
extern u8 bob_dl_library_books_ci4[];
extern u8 bob_dl_library_books_ci4_pal_rgba16[];
extern u8 bob_dl_library_floor_rgba16[];
extern u8 bob_dl_library_book_ci4[];
extern u8 bob_dl_library_book_ci4_pal_rgba16[];
extern u8 bob_dl_sign_ci4[];
extern u8 bob_dl_sign_ci4_pal_rgba16[];
extern u8 bob_dl_library_floor_ci4[];
extern u8 bob_dl_library_floor_ci4_pal_rgba16[];
extern u8 bob_dl_light_2_rgba32[];
extern Vtx bob_dl_Cube_mesh_layer_1_vtx_0[38];
extern Gfx bob_dl_Cube_mesh_layer_1_tri_0[];
extern Vtx bob_dl_Cube_mesh_layer_1_vtx_1[44];
extern Gfx bob_dl_Cube_mesh_layer_1_tri_1[];
extern Vtx bob_dl_Cube_mesh_layer_1_vtx_2[124];
extern Gfx bob_dl_Cube_mesh_layer_1_tri_2[];
extern Vtx bob_dl_Cube_mesh_layer_1_vtx_3[43];
extern Gfx bob_dl_Cube_mesh_layer_1_tri_3[];
extern Vtx bob_dl_Cube_mesh_layer_1_vtx_4[4];
extern Gfx bob_dl_Cube_mesh_layer_1_tri_4[];
extern Vtx bob_dl_Cube_mesh_layer_2_vtx_0[39];
extern Gfx bob_dl_Cube_mesh_layer_2_tri_0[];
extern Vtx bob_dl_Cube_mesh_layer_2_vtx_1[8];
extern Gfx bob_dl_Cube_mesh_layer_2_tri_1[];
extern Vtx bob_dl_Cube_001_mesh_layer_2_vtx_0[19];
extern Gfx bob_dl_Cube_001_mesh_layer_2_tri_0[];
extern Vtx bob_dl_Cube_001_mesh_layer_1_vtx_0[48];
extern Gfx bob_dl_Cube_001_mesh_layer_1_tri_0[];
extern Vtx bob_dl_Cube_001_mesh_layer_1_vtx_1[28];
extern Gfx bob_dl_Cube_001_mesh_layer_1_tri_1[];
extern Vtx bob_dl_Cube_001_mesh_layer_1_vtx_2[4];
extern Gfx bob_dl_Cube_001_mesh_layer_1_tri_2[];
extern Vtx bob_dl_Cube_001_mesh_layer_1_vtx_3[4];
extern Gfx bob_dl_Cube_001_mesh_layer_1_tri_3[];
extern Vtx bob_dl_Cube_002_mesh_layer_1_vtx_0[206];
extern Gfx bob_dl_Cube_002_mesh_layer_1_tri_0[];
extern Vtx bob_dl_Cube_002_mesh_layer_1_vtx_1[68];
extern Gfx bob_dl_Cube_002_mesh_layer_1_tri_1[];
extern Vtx bob_dl_Cube_002_mesh_layer_1_vtx_2[34];
extern Gfx bob_dl_Cube_002_mesh_layer_1_tri_2[];
extern Vtx bob_dl_Cube_002_mesh_layer_1_vtx_3[126];
extern Gfx bob_dl_Cube_002_mesh_layer_1_tri_3[];
extern Vtx bob_dl_Cube_002_mesh_layer_1_vtx_4[4];
extern Gfx bob_dl_Cube_002_mesh_layer_1_tri_4[];
extern Vtx bob_dl_Cube_002_mesh_layer_2_vtx_0[24];
extern Gfx bob_dl_Cube_002_mesh_layer_2_tri_0[];
extern Vtx bob_dl_Cube_007_mesh_layer_1_vtx_0[6];
extern Gfx bob_dl_Cube_007_mesh_layer_1_tri_0[];
extern Vtx bob_dl_Cube_004_mesh_layer_2_vtx_0[19];
extern Gfx bob_dl_Cube_004_mesh_layer_2_tri_0[];
extern Vtx bob_dl_Cube_004_mesh_layer_1_vtx_0[48];
extern Gfx bob_dl_Cube_004_mesh_layer_1_tri_0[];
extern Vtx bob_dl_Cube_004_mesh_layer_1_vtx_1[28];
extern Gfx bob_dl_Cube_004_mesh_layer_1_tri_1[];
extern Vtx bob_dl_Cube_004_mesh_layer_1_vtx_2[4];
extern Gfx bob_dl_Cube_004_mesh_layer_1_tri_2[];
extern Vtx bob_dl_Cube_004_mesh_layer_1_vtx_3[4];
extern Gfx bob_dl_Cube_004_mesh_layer_1_tri_3[];
extern Vtx bob_dl_Cube_003_mesh_layer_1_vtx_0[39];
extern Gfx bob_dl_Cube_003_mesh_layer_1_tri_0[];
extern Vtx bob_dl_Cube_003_mesh_layer_1_vtx_1[44];
extern Gfx bob_dl_Cube_003_mesh_layer_1_tri_1[];
extern Vtx bob_dl_Cube_003_mesh_layer_1_vtx_2[124];
extern Gfx bob_dl_Cube_003_mesh_layer_1_tri_2[];
extern Vtx bob_dl_Cube_003_mesh_layer_1_vtx_3[43];
extern Gfx bob_dl_Cube_003_mesh_layer_1_tri_3[];
extern Vtx bob_dl_Cube_003_mesh_layer_1_vtx_4[4];
extern Gfx bob_dl_Cube_003_mesh_layer_1_tri_4[];
extern Vtx bob_dl_Cube_003_mesh_layer_2_vtx_0[60];
extern Gfx bob_dl_Cube_003_mesh_layer_2_tri_0[];
extern Vtx bob_dl_Cube_003_mesh_layer_2_vtx_1[4];
extern Gfx bob_dl_Cube_003_mesh_layer_2_tri_1[];
extern Vtx bob_dl_Cube_006_mesh_layer_5_vtx_0[12];
extern Gfx bob_dl_Cube_006_mesh_layer_5_tri_0[];
extern Gfx mat_bob_dl_f3dlite_material_001[];
extern Gfx mat_revert_bob_dl_f3dlite_material_001[];
extern Gfx mat_bob_dl_f3dlite_material_003_layer2[];
extern Gfx mat_revert_bob_dl_f3dlite_material_003_layer2[];
extern Gfx mat_bob_dl_f3dlite_material_002[];
extern Gfx mat_revert_bob_dl_f3dlite_material_002[];
extern Gfx mat_bob_dl_f3dlite_material[];
extern Gfx mat_revert_bob_dl_f3dlite_material[];
extern Gfx mat_bob_dl_f3dlite_material_004[];
extern Gfx mat_revert_bob_dl_f3dlite_material_004[];
extern Gfx mat_bob_dl_f3dlite_material_005_layer2[];
extern Gfx mat_revert_bob_dl_f3dlite_material_005_layer2[];
extern Gfx mat_bob_dl_instant_warp[];
extern Gfx mat_revert_bob_dl_instant_warp[];
extern Gfx mat_bob_dl_instant_warp_1b[];
extern Gfx mat_revert_bob_dl_instant_warp_1b[];
extern Gfx mat_bob_dl_f3dlite_material_006[];
extern Gfx mat_revert_bob_dl_f3dlite_material_006[];
extern Gfx mat_bob_dl_f3dlite_material_008[];
extern Gfx mat_revert_bob_dl_f3dlite_material_008[];
extern Gfx mat_bob_dl_f3dlite_material_007[];
extern Gfx mat_revert_bob_dl_f3dlite_material_007[];
extern Gfx bob_dl_Cube_mesh_layer_1[];
extern Gfx bob_dl_Cube_mesh_layer_2[];
extern Gfx bob_dl_Cube_001_mesh_layer_2[];
extern Gfx bob_dl_Cube_001_mesh_layer_1[];
extern Gfx bob_dl_Cube_002_mesh_layer_1[];
extern Gfx bob_dl_Cube_002_mesh_layer_2[];
extern Gfx bob_dl_Cube_007_mesh_layer_1[];
extern Gfx bob_dl_Cube_004_mesh_layer_2[];
extern Gfx bob_dl_Cube_004_mesh_layer_1[];
extern Gfx bob_dl_Cube_003_mesh_layer_1[];
extern Gfx bob_dl_Cube_003_mesh_layer_2[];
extern Gfx bob_dl_Cube_006_mesh_layer_5[];
extern Gfx bob_dl_material_revert_render_settings[];
