#include "src/game/envfx_snow.h"

const GeoLayout dark_twoser_geo[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 63, 0, NULL),
		GEO_OPEN_NODE(),
			GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 99, 0, 10, 0, 0),
			GEO_OPEN_NODE(),
				GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, dark_twoser_Pelvis_mesh_layer_1),
				GEO_OPEN_NODE(),
					GEO_DISPLAY_LIST(LAYER_TRANSPARENT, dark_twoser_Pelvis_mesh_layer_5),
					GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 79, 0, -67, 0, 0),
					GEO_OPEN_NODE(),
						GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, dark_twoser_Shell_mesh_layer_1),
					GEO_CLOSE_NODE(),
					GEO_DISPLAY_LIST(LAYER_OPAQUE, dark_twoser_Tail_skinned_mesh_layer_1),
					GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 13, -61, 34, 0, 180),
					GEO_OPEN_NODE(),
						GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, dark_twoser_Tail_mesh_layer_1),
					GEO_CLOSE_NODE(),
					GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 57, 43, -7, -17, 0, -180),
					GEO_OPEN_NODE(),
						GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, dark_twoser_Thigh_L_mesh_layer_1),
						GEO_OPEN_NODE(),
							GEO_DISPLAY_LIST(LAYER_OPAQUE, dark_twoser_Shin_L_skinned_mesh_layer_1),
							GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 59, 0, -14, 0, 0),
							GEO_OPEN_NODE(),
								GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, dark_twoser_Shin_L_mesh_layer_1),
								GEO_OPEN_NODE(),
									GEO_DISPLAY_LIST(LAYER_OPAQUE, dark_twoser_Foot_L_skinned_mesh_layer_1),
									GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 69, 0, 97, 0, 0),
									GEO_OPEN_NODE(),
										GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, dark_twoser_Foot_L_mesh_layer_1),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
					GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, -57, 43, -7, -17, 0, 180),
					GEO_OPEN_NODE(),
						GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, dark_twoser_Thigh_R_mesh_layer_1),
						GEO_OPEN_NODE(),
							GEO_DISPLAY_LIST(LAYER_OPAQUE, dark_twoser_Shin_R_skinned_mesh_layer_1),
							GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 59, 0, -14, 0, 0),
							GEO_OPEN_NODE(),
								GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, dark_twoser_Shin_R_mesh_layer_1),
								GEO_OPEN_NODE(),
									GEO_DISPLAY_LIST(LAYER_OPAQUE, dark_twoser_Foot_R_skinned_mesh_layer_1),
									GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 69, 0, 97, 0, 0),
									GEO_OPEN_NODE(),
										GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, dark_twoser_Foot_R_mesh_layer_1),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
					GEO_DISPLAY_LIST(LAYER_OPAQUE, dark_twoser_Torso_skinned_mesh_layer_1),
					GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 79, 0, 21, 0, 0),
					GEO_OPEN_NODE(),
						GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, dark_twoser_Torso_mesh_layer_1),
						GEO_OPEN_NODE(),
							GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 56, 118, 2, -31, 0, -90),
							GEO_OPEN_NODE(),
								GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, dark_twoser_Bicept_L_mesh_layer_1),
								GEO_OPEN_NODE(),
									GEO_DISPLAY_LIST(LAYER_OPAQUE, dark_twoser_Tricep_L_skinned_mesh_layer_1),
									GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 84, 0, dark_twoser_Tricep_L_mesh_layer_1),
									GEO_OPEN_NODE(),
										GEO_DISPLAY_LIST(LAYER_OPAQUE, dark_twoser_Hand_L_skinned_mesh_layer_1),
										GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 47, 0, dark_twoser_Hand_L_mesh_layer_1),
										GEO_OPEN_NODE(),
											GEO_DISPLAY_LIST(LAYER_OPAQUE, dark_twoser_Middle_L_skinned_mesh_layer_1),
											GEO_ANIMATED_PART(LAYER_OPAQUE, -12, 53, -6, dark_twoser_Middle_L_mesh_layer_1),
											GEO_DISPLAY_LIST(LAYER_OPAQUE, dark_twoser_Pinky_L_skinned_mesh_layer_1),
											GEO_ANIMATED_PART(LAYER_OPAQUE, -24, 46, -23, dark_twoser_Pinky_L_mesh_layer_1),
											GEO_DISPLAY_LIST(LAYER_OPAQUE, dark_twoser_Pointer_L_skinned_mesh_layer_1),
											GEO_ANIMATED_PART(LAYER_OPAQUE, -2, 53, 15, dark_twoser_Pointer_L_mesh_layer_1),
											GEO_DISPLAY_LIST(LAYER_OPAQUE, dark_twoser_Thumb_L_skinned_mesh_layer_1),
											GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 29, 28, 17, 6, -1, -8),
											GEO_OPEN_NODE(),
												GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, dark_twoser_Thumb_L_mesh_layer_1),
											GEO_CLOSE_NODE(),
										GEO_CLOSE_NODE(),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
							GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, -56, 118, 2, -31, 0, 90),
							GEO_OPEN_NODE(),
								GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, dark_twoser_Bicept_R_mesh_layer_1),
								GEO_OPEN_NODE(),
									GEO_DISPLAY_LIST(LAYER_OPAQUE, dark_twoser_Tricep_R_skinned_mesh_layer_1),
									GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 84, 0, dark_twoser_Tricep_R_mesh_layer_1),
									GEO_OPEN_NODE(),
										GEO_DISPLAY_LIST(LAYER_OPAQUE, dark_twoser_Hand_R_skinned_mesh_layer_1),
										GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 47, 0, dark_twoser_Hand_R_mesh_layer_1),
										GEO_OPEN_NODE(),
											GEO_DISPLAY_LIST(LAYER_OPAQUE, dark_twoser_Middle_R_skinned_mesh_layer_1),
											GEO_ANIMATED_PART(LAYER_OPAQUE, 12, 53, -6, dark_twoser_Middle_R_mesh_layer_1),
											GEO_DISPLAY_LIST(LAYER_OPAQUE, dark_twoser_Pinky_R_skinned_mesh_layer_1),
											GEO_ANIMATED_PART(LAYER_OPAQUE, 24, 46, -23, dark_twoser_Pinky_R_mesh_layer_1),
											GEO_DISPLAY_LIST(LAYER_OPAQUE, dark_twoser_Pointer_R_skinned_mesh_layer_1),
											GEO_ANIMATED_PART(LAYER_OPAQUE, 2, 53, 15, dark_twoser_Pointer_R_mesh_layer_1),
											GEO_DISPLAY_LIST(LAYER_OPAQUE, dark_twoser_Thumb_R_skinned_mesh_layer_1),
											GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, -29, 28, 17, 6, 1, 8),
											GEO_OPEN_NODE(),
												GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, dark_twoser_Thumb_R_mesh_layer_1),
											GEO_CLOSE_NODE(),
										GEO_CLOSE_NODE(),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
							GEO_DISPLAY_LIST(LAYER_OPAQUE, dark_twoser_Head_skinned_mesh_layer_1),
							GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 143, 0, 27, 0, 0),
							GEO_OPEN_NODE(),
								GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, dark_twoser_Head_mesh_layer_1),
								GEO_OPEN_NODE(),
									GEO_DISPLAY_LIST(LAYER_ALPHA, dark_twoser_Head_mesh_layer_4),
									GEO_DISPLAY_LIST(LAYER_OPAQUE_DECAL, dark_twoser_Head_mesh_layer_2),
									GEO_DISPLAY_LIST(LAYER_OPAQUE, dark_twoser_Jaw_skinned_mesh_layer_1),
									GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 27, 25, -73, -180, 0),
									GEO_OPEN_NODE(),
										GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, dark_twoser_Jaw_mesh_layer_1),
										GEO_OPEN_NODE(),
											GEO_DISPLAY_LIST(LAYER_ALPHA, dark_twoser_Jaw_mesh_layer_4),
										GEO_CLOSE_NODE(),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
			GEO_SHADOW(0, 204, 300),
		GEO_CLOSE_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, dark_twoser_material_revert_render_settings),
		GEO_DISPLAY_LIST(LAYER_OPAQUE_DECAL, dark_twoser_material_revert_render_settings),
		GEO_DISPLAY_LIST(LAYER_ALPHA, dark_twoser_material_revert_render_settings),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, dark_twoser_material_revert_render_settings),
	GEO_CLOSE_NODE(),
	GEO_END(),
};
