#include "src/game/envfx_snow.h"

const GeoLayout twoser_geo[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
		GEO_OPEN_NODE(),
			GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 109, 5, twoser_Waist_mesh_layer_1),
			GEO_OPEN_NODE(),
				GEO_DISPLAY_LIST(LAYER_OPAQUE, twoser_Chest_skinned_mesh_layer_1),
				GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 127, 26, twoser_Chest_mesh_layer_1),
				GEO_OPEN_NODE(),
					GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 59, 48, twoser_Head_mesh_layer_1),
					GEO_OPEN_NODE(),
						GEO_DISPLAY_LIST(LAYER_ALPHA, twoser_Head_mesh_layer_4),
						GEO_DISPLAY_LIST(LAYER_OPAQUE_DECAL, twoser_Head_mesh_layer_2),
						GEO_DISPLAY_LIST(LAYER_OPAQUE, twoser_Jaw_skinned_mesh_layer_1),
						GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 2, 55, twoser_Jaw_mesh_layer_1),
						GEO_OPEN_NODE(),
							GEO_DISPLAY_LIST(LAYER_ALPHA, twoser_Jaw_mesh_layer_4),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
					GEO_DISPLAY_LIST(LAYER_OPAQUE, twoser_Left_arm_1_skinned_mesh_layer_1),
					GEO_ANIMATED_PART(LAYER_OPAQUE, 68, 24, 47, twoser_Left_arm_1_mesh_layer_1),
					GEO_OPEN_NODE(),
						GEO_DISPLAY_LIST(LAYER_OPAQUE, twoser_Left_Arm_2_skinned_mesh_layer_1),
						GEO_ANIMATED_PART(LAYER_OPAQUE, 54, -12, 4, twoser_Left_Arm_2_mesh_layer_1),
						GEO_OPEN_NODE(),
							GEO_DISPLAY_LIST(LAYER_OPAQUE, twoser_Left_Hand_skinned_mesh_layer_1),
							GEO_ANIMATED_PART(LAYER_OPAQUE, 68, -4, -3, twoser_Left_Hand_mesh_layer_1),
							GEO_OPEN_NODE(),
								GEO_DISPLAY_LIST(LAYER_OPAQUE, twoser_Left_Middle_skinned_mesh_layer_1),
								GEO_ANIMATED_PART(LAYER_OPAQUE, 49, 50, -10, twoser_Left_Middle_mesh_layer_1),
								GEO_DISPLAY_LIST(LAYER_OPAQUE, twoser_Left_Pinky_skinned_mesh_layer_1),
								GEO_ANIMATED_PART(LAYER_OPAQUE, 49, 59, -31, twoser_Left_Pinky_mesh_layer_1),
								GEO_DISPLAY_LIST(LAYER_OPAQUE, twoser_Left_Pointer_skinned_mesh_layer_1),
								GEO_ANIMATED_PART(LAYER_OPAQUE, 48, 41, 10, twoser_Left_Pointer_mesh_layer_1),
								GEO_DISPLAY_LIST(LAYER_OPAQUE, twoser_Left_Thumb_skinned_mesh_layer_1),
								GEO_ANIMATED_PART(LAYER_OPAQUE, 32, -6, 17, twoser_Left_Thumb_mesh_layer_1),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
					GEO_DISPLAY_LIST(LAYER_OPAQUE, twoser_Right_arm_1_skinned_mesh_layer_1),
					GEO_ANIMATED_PART(LAYER_OPAQUE, -68, 24, 47, twoser_Right_arm_1_mesh_layer_1),
					GEO_OPEN_NODE(),
						GEO_DISPLAY_LIST(LAYER_OPAQUE, twoser_Right_Arm_2_skinned_mesh_layer_1),
						GEO_ANIMATED_PART(LAYER_OPAQUE, -54, -12, 4, twoser_Right_Arm_2_mesh_layer_1),
						GEO_OPEN_NODE(),
							GEO_DISPLAY_LIST(LAYER_OPAQUE, twoser_Right_Hand_skinned_mesh_layer_1),
							GEO_ANIMATED_PART(LAYER_OPAQUE, -68, -4, -3, twoser_Right_Hand_mesh_layer_1),
							GEO_OPEN_NODE(),
								GEO_DISPLAY_LIST(LAYER_OPAQUE, twoser_Right_Middle_skinned_mesh_layer_1),
								GEO_ANIMATED_PART(LAYER_OPAQUE, -49, 50, -10, twoser_Right_Middle_mesh_layer_1),
								GEO_DISPLAY_LIST(LAYER_OPAQUE, twoser_Right_Pinky_skinned_mesh_layer_1),
								GEO_ANIMATED_PART(LAYER_OPAQUE, -49, 59, -31, twoser_Right_Pinky_mesh_layer_1),
								GEO_DISPLAY_LIST(LAYER_OPAQUE, twoser_Right_Pointer_skinned_mesh_layer_1),
								GEO_ANIMATED_PART(LAYER_OPAQUE, -48, 41, 10, twoser_Right_Pointer_mesh_layer_1),
								GEO_DISPLAY_LIST(LAYER_OPAQUE, twoser_Right_Thumb_skinned_mesh_layer_1),
								GEO_ANIMATED_PART(LAYER_OPAQUE, -32, -6, 17, twoser_Right_Thumb_mesh_layer_1),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
				GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 38, 57, twoser_Shell_mesh_layer_1),
				GEO_DISPLAY_LIST(LAYER_OPAQUE, twoser_Tail_skinned_mesh_layer_1),
				GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 15, -50, twoser_Tail_mesh_layer_1),
				GEO_DISPLAY_LIST(LAYER_OPAQUE, twoser_left_leg_1_skinned_mesh_layer_1),
				GEO_ANIMATED_PART(LAYER_OPAQUE, 56, -1, -7, twoser_left_leg_1_mesh_layer_1),
				GEO_OPEN_NODE(),
					GEO_DISPLAY_LIST(LAYER_OPAQUE, twoser_left_leg_2_skinned_mesh_layer_1),
					GEO_ANIMATED_PART(LAYER_OPAQUE, 0, -58, -13, twoser_left_leg_2_mesh_layer_1),
				GEO_CLOSE_NODE(),
				GEO_DISPLAY_LIST(LAYER_OPAQUE, twoser_right_leg_1_skinned_mesh_layer_1),
				GEO_ANIMATED_PART(LAYER_OPAQUE, -56, -1, -7, twoser_right_leg_1_mesh_layer_1),
				GEO_OPEN_NODE(),
					GEO_DISPLAY_LIST(LAYER_OPAQUE, twoser_right_leg_2_skinned_mesh_layer_1),
					GEO_ANIMATED_PART(LAYER_OPAQUE, 0, -58, -13, twoser_right_leg_2_mesh_layer_1),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
			GEO_SHADOW(1, 204, 350),
		GEO_CLOSE_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, twoser_material_revert_render_settings),
		GEO_DISPLAY_LIST(LAYER_OPAQUE_DECAL, twoser_material_revert_render_settings),
		GEO_DISPLAY_LIST(LAYER_ALPHA, twoser_material_revert_render_settings),
	GEO_CLOSE_NODE(),
	GEO_END(),
};
