extern const GeoLayout ddd_area_1_geo[];
extern const GeoLayout ddd_area_1[];
extern const Collision ddd_area_1_collision[];
extern const MacroObject ddd_area_1_macro_objs[];
extern u8 ddd_dl_road_ci4[];
extern u8 ddd_dl_road_ci4_pal_rgba16[];
extern u8 ddd_dl_fountain_1_ci8[];
extern u8 ddd_dl_fountain_1_ci8_pal_rgba16[];
extern u8 ddd_dl_fountain_2_ia8[];
extern Vtx ddd_dl_Cube_mesh_layer_1_vtx_0[14];
extern Gfx ddd_dl_Cube_mesh_layer_1_tri_0[];
extern Vtx ddd_dl_Cube_001_mesh_layer_4_vtx_0[4];
extern Gfx ddd_dl_Cube_001_mesh_layer_4_tri_0[];
extern Vtx ddd_dl_Cube_001_mesh_layer_5_vtx_0[8];
extern Gfx ddd_dl_Cube_001_mesh_layer_5_tri_0[];
extern Gfx mat_ddd_dl_f3dlite_material[];
extern Gfx mat_revert_ddd_dl_f3dlite_material[];
extern Gfx mat_ddd_dl_f3dlite_material_001[];
extern Gfx mat_revert_ddd_dl_f3dlite_material_001[];
extern Gfx mat_ddd_dl_f3dlite_material_002[];
extern Gfx mat_revert_ddd_dl_f3dlite_material_002[];
extern Gfx ddd_dl_Cube_mesh_layer_1[];
extern Gfx ddd_dl_Cube_001_mesh_layer_4[];
extern Gfx ddd_dl_Cube_001_mesh_layer_5[];
extern Gfx ddd_dl_material_revert_render_settings[];
